// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbulRMsrz0pW5ErM5Z2GdafgccB9oKq2Q',
    appId: '1:584164274459:web:eaa8102ffba5b96908e3be',
    messagingSenderId: '584164274459',
    projectId: 'qantara-53495',
    authDomain: 'qantara-53495.firebaseapp.com',
    storageBucket: 'qantara-53495.firebasestorage.app',
    measurementId: 'G-KYZ844BJRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwqR7IRht58JMLYuxwl7uMheI0VwX9mkA',
    appId: '1:584164274459:android:039f06a6b76019bc08e3be',
    messagingSenderId: '584164274459',
    projectId: 'qantara-53495',
    storageBucket: 'qantara-53495.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyx7vEh9V8e_j9q3WQHDsJZY6WFDq1-BQ',
    appId: '1:584164274459:ios:64220a69187fb0ac08e3be',
    messagingSenderId: '584164274459',
    projectId: 'qantara-53495',
    storageBucket: 'qantara-53495.firebasestorage.app',
    iosBundleId: 'com.example.qantara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyx7vEh9V8e_j9q3WQHDsJZY6WFDq1-BQ',
    appId: '1:584164274459:ios:64220a69187fb0ac08e3be',
    messagingSenderId: '584164274459',
    projectId: 'qantara-53495',
    storageBucket: 'qantara-53495.firebasestorage.app',
    iosBundleId: 'com.example.qantara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbulRMsrz0pW5ErM5Z2GdafgccB9oKq2Q',
    appId: '1:584164274459:web:1c6ad2e79051fe8a08e3be',
    messagingSenderId: '584164274459',
    projectId: 'qantara-53495',
    authDomain: 'qantara-53495.firebaseapp.com',
    storageBucket: 'qantara-53495.firebasestorage.app',
    measurementId: 'G-DTPD0H06HM',
  );
}
